# Generated by Django 4.1.3 on 2023-11-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humidity', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensorreadings',
            unique_together={('Node_id', 'Timestamp')},
        ),
    ]
