CREATE TABLE IF NOT EXISTS "sensors" (
    "Node_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Latitude" DECIMAL NOT NULL,
    "Longitude" DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS "sensorReadings" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Temperature" REAL NOT NULL,
    "Humidity" REAL NOT NULL,
    "Timestamp" DATETIME NOT NULL,
    "Node_id_id" INTEGER NOT NULL REFERENCES "sensors" ("Node_id") DEFERRABLE INITIALLY DEFERRED
);

